version: '2'

services:

        messageEngine:
                image: sidgoyal/messaging-server
                container_name: messageEngine

        derby:
                image: sidgoyal/derby-server
                container_name: derby
                depends_on:
                      - messageEngine


        dispatcher:
                image: sidgoyal/bonuspayout-app:dispatcherServer
                container_name: dispatcher
                depends_on:
                       - messageEngine
                       - derby
                environment:
                       DERBY_HOST: derby
                       MESSAGE_HOST: messageEngine

                ports:
                       - "8443:9443"
                       - "8080:9080"
                links:
                       - derby
                       - messageEngine
                volumes:
                       - csv:/csv

        executor:
                image: sidgoyal/bonuspayout-app:executorServer
                container_name: executor
                depends_on:
                       - messageEngine
                       - derby
                       - dispatcher
                links:
                       - derby
                       - messageEngine

                volumes:
                       - csv:/csv

        results:
                image: sidgoyal/bonuspayout.results.api
                depends_on:
                        - executor
                container_name: results
                ports:
                        - "7443:9443"
                        - "7080:9080"
                volumes:
                        - csv:/csv

volumes:
        csv:


